name: firebase_auth_crud_social_media_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^5.0.1
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  firebase_storage: ^12.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_markdown: ^0.7.2+1
  form_map: ^0.1.0
  go_router: ^14.2.0
  hydrated_bloc: ^9.1.5
  image_picker: ^1.1.2
  image_picker_for_web: ^3.0.4
  path_provider: ^2.1.3
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
