// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUFiW2ttCSUv4wXcH71j9U_8BM2xa385o',
    appId: '1:1076432994661:web:7a434dba914d7dced0618c',
    messagingSenderId: '1076432994661',
    projectId: 'social-auth-crud',
    authDomain: 'social-auth-crud.firebaseapp.com',
    storageBucket: 'social-auth-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmo8dM7DA8s1OaD1jJf1jt6tAAumHW5lc',
    appId: '1:1076432994661:android:0807e34e5598dd89d0618c',
    messagingSenderId: '1076432994661',
    projectId: 'social-auth-crud',
    storageBucket: 'social-auth-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAug7PSewWomn-M8KwO922t9W_OecyQgOA',
    appId: '1:1076432994661:ios:a6b4add3b7bc3b5ad0618c',
    messagingSenderId: '1076432994661',
    projectId: 'social-auth-crud',
    storageBucket: 'social-auth-crud.appspot.com',
    iosBundleId: 'com.example.firebaseAuthCrudSocialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAug7PSewWomn-M8KwO922t9W_OecyQgOA',
    appId: '1:1076432994661:ios:a6b4add3b7bc3b5ad0618c',
    messagingSenderId: '1076432994661',
    projectId: 'social-auth-crud',
    storageBucket: 'social-auth-crud.appspot.com',
    iosBundleId: 'com.example.firebaseAuthCrudSocialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUFiW2ttCSUv4wXcH71j9U_8BM2xa385o',
    appId: '1:1076432994661:web:db017727af512627d0618c',
    messagingSenderId: '1076432994661',
    projectId: 'social-auth-crud',
    authDomain: 'social-auth-crud.firebaseapp.com',
    storageBucket: 'social-auth-crud.appspot.com',
  );
}
